services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'false'
      MYSQL_USER: admin
      MYSQL_PASSWORD: Abc@12345
      MYSQL_DATABASE: Test
      TZ: 'utc'
    command: --default-authentication-plugin=mysql_native_password
